blank_issues_enabled: false
contact_links:
  - name: Questions, Help and Discussions
    url: https://github.com/bytedance/bhook/discussions
    about: Looking for help and discuss general questions.
